namespace WeenyMapper.Docs.Samples
{
    public class Movie
    {
        // Generated by identity in the database
        public int Id { get; set; }
        public string Title { get; set; }
        public string Director { get; set; }
    }
}